# Generic make file for LaTeX: requires GNU make
#
# This makefile provides four targets: dvi, ps, pdf and clean.
# The default is "pdf".
# To make a dvi file, type "make dvi"
# To make a ps file, type "make ps".
# To make a pdf file, type "make pdf" or simply "make".
# To remove all files generated by make, type "make clean".
#
# Rouben Rostmaian <rostamian@umbc.edu>
# September 2002
#
# September 2005: Added the -o flag to dvips.  Thanks
# to Juan J. Merelo Guervós <jmerelo@geneura.ugr.es>

GREP=grep
PDFLATEX=pdflatex

#TEXFILE	= slides.tex
TEXFILES	= MATH110-Syllabus.tex
SUBDIRS		= $(wildcard LE* PS* FE FS MT* QZ* SF* SG)

.PHONY: default
default: ts subdirs

.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@ $(MAKECMDGOALS)

#.PHONY: aux dvi pdf ps clean view
.PHONY: pdf ps dvi ts clean distclean makefiles view

pdf:	$(TEXFILES:.tex=.pdf)
ps:	$(TEXFILES:.tex=.ps)
dvi:	$(TEXFILES:.tex=.dvi)
ts:	$(TEXFILES:.tex=.ts)

work:
	(find . -name '*.tex' -exec grep -l fixme {} \;) | sort 
	(find . -name '*.tex' -exec grep -l FIXME {} \;) | sort 
	(find . -name '*.tex' -exec grep -l ejd {} \;) | sort 
	(find . -name '*.tex' -exec grep -l EJD {} \;) | sort 

#%.dvi: %.tex
#	( \
#	latex $<; \
#	while grep -q "Rerun to get cross-references right." $(<:.tex=.log); \
#	do \
#		latex $<; \
#	done \
#	)

%.pdf: %.tex common.tex
	( \
	$(PDFLATEX) $<; \
	while $(GREP) -q "rerunfilecheck Warning" $(<:.tex=.log); \
	do \
		$(PDFLATEX) $<; \
	done \
	)

%.ts: %.pdf
	cp $< PDFs/
	touch $(<:.pdf=.ts)

#%.ps: %.dvi
#	dvips -q -t a4 $< -o $(<:.dvi=.ps)

#%.ps: %.dvi
#	dvips -q $< -o $(<:.dvi=.ps)

#%.pdf: %.ps
#	ps2pdf -dPDFSETTINGS=/prepress $<

#%.pdf: %.dvi
#	latex $<

clean: $(SUBDIRS)
	@rm -f \
	$(TEXFILES:.tex=.dvi) \
	$(TEXFILES:.tex=.pdf) \
	$(TEXFILES:.tex=.ps)  \
	$(TEXFILES:.tex=.ts)  \
	@rm -f PDFs/*.pdf

distclean: $(SUBDIRS)
	@rm -f \
	$(TEXFILES:.tex=.aux) \
	$(TEXFILES:.tex=.log) \
	$(TEXFILES:.tex=.out) \
	$(TEXFILES:.tex=.dvi) \
	$(TEXFILES:.tex=.pdf) \
	$(TEXFILES:.tex=.ps)  \
	$(TEXFILES:.tex=.ts)

makefiles:
	echo $(SUBDIRS) | xargs -n 1 cp Make/Makefile

#view: $(TEXFILE:.tex=.ps)
#	gv -landscape $(TEXFILES:.tex=.ps) &

#view: $(TEXFILE:.tex=.pdf)
#	acroread $(TEXFILES:.tex=.pdf) &

#view: $(TEXFILES:.tex=.pdf)
#	/cygdrive/c/Users/edwar/AppData/Local/SumatraPDF/SumatraPDF.exe $(TEXFILES:.tex=.pdf) &

view: $(TEXFILES:.tex=.pdf)
	$(PDFVIEWER) & sleep 3
	$(foreach var,$(TEXFILES:.tex=.pdf), $(PDFVIEWER) $(var) & sleep 3 & )


